version: '2'
services:
  proxy_pool_lite:
    build: .
    container_name: proxy_pool_lite
    restart: always
    ports:
      - "33001:33001"
    depends_on:
      - redis
    links:
      - redis
  redis:
    image: "redis"
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
